plugins {
    id 'com.android.library'
}

ext.pluginVersionCode = 7
ext.pluginVersionName = "5.0.0"

android {
    namespace "com.android.library"
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        minSdk 29
        targetSdk 35
        versionCode pluginVersionCode
        versionName pluginVersionName
    }
    ndkVersion '28.1.13356709'

    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "GodotGooglePlayBilling.$pluginVersionName.${variant.name}.aar"
        }
    }
}

dependencies {
    implementation 'com.android.billingclient:billing:8.1.0'
    compileOnly fileTree(dir: 'libs', include: ['godot-lib.4.5.1.stable.template_release*.aar'])
}
